name: Déploiement Web sur GitHub Pages

on:
  push:
    branches: [ main ] # L'application se mettra à jour en ligne à chaque fois que tu fais un git push !
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # On utilise Linux cette fois, c'est plus rapide pour le Web

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Activer le Web
        run: flutter config --enable-web

      - name: Installer les dépendances
        run: flutter pub get

      - name: Compiler pour le Web
        # ⚠️ TRÈS IMPORTANT : Remplace "NOM_DU_DEPOT" par le nom exact de ton projet sur GitHub
        run: flutter build web --release --base-href "/jeux151/"

      - name: Déployer sur Internet
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
